---
language: ruby

jobs:
  include:
    # 10.14 Mojave
    - os: osx
      osx_image: xcode11.3
    # 10.13 High Sierra
    - os: osx
      osx_image: xcode10.1
    # 10.12 Sierra
    - os: osx
      osx_image: xcode9.2

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

script:
  - bin/travis-build.sh
  - bin/show-font-version.py

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "qnOCekMUP9XujvgoAFrIzDZyHN/jbxaLWKN4phjGbWvECzwGNE0cFLD3oHTH/YbT\
               Rhe1247J4mRg/5Ye/I1UWWyvqt3VzIDokd3U0qwA0vNoM6B68YJt0BLHl99Kgm8L\
               GUBQ6/QgFtwb7ANEBKaSknVxE1gv0NeiQEeTMobRTF6VaCdEnvU0uTirAODkF/CW\
               aKE8UTGrwqJJXLcKK1WKf8gwHOS5duFFQa8j8BrYfk739eGfW3oO29elHVlpdLJq\
               FrAThKLQlaJYXRAPtgLdrdYYldMUuT3W2gwPW5G7XTKr74+OD57JASvLVrkkyocs\
               8P6kAdto7ol9Ypg3NUUXIH/MSyQ5XOi9lArEktbQwHK9v8obF1JsFCne3sOEVOLr\
               okczXPZw37o0qz16PqbcQw09tQicwnwVStGcJRegyAZlUFxk3CRvAbPE/Hqoy66m\
               CMp8GxZLNtMliR/KMjJWSAHrAFTl+ehGV1XhLMxi6Qx8/jNFxSza+G+qLmFhhHBi\
               M0qnP+zJ/j2Bkzf5SvNBd1txSqYtm9jgAi0UH4qfcyDtFvc9+BhddmCg9oRhpNZ5\
               GmHrBOPcoXOY8J52B5XQpeK+5/KzZ3E6JG/dyTPWXqiDJJVyrQiUTIRJgoXmgnYL\
               xtCRizFazqkCB4e3Xhz5PQrLzwvA+pXyhsMtYtQ1heY="
