#!/usr/bin/env perl
use v5.14;
use warnings;

die unless defined $ARGV[0];
my $version = "0.1.$ARGV[0]";
cmd('git', 'tag', "v$version");
cmd('git', 'push', '--tags');
my $formula = 'sfmono-square.rb';
open my $in, '<', $formula or die;
my $old = do { local $/; <$in> };
close $in;
open my $out, '>', $formula or die;
my $hash;
for my $line (split /\n/, $old) {
    if ($line =~ /^  url/) {
        $line =~ s,[^/]+"$,v$version.tar.gz",;
        my ($url) = $line =~ /url "(.*)"/;
        $hash = cmd_out('curl', '-L', $url, '|', 'shasum', '-a256');
    }
    elsif ($line =~ /^  sha256/) { $line =~ s/".*"/"$hash"/ }
    elsif ($line =~ /^  version/) { $line =~ s/".*"/"$version"/ }
    $out->say($line);
}
close $out;
cmd('git', 'add', '*');
cmd('git', 'commit', '-m', "Bump version up to v$version");

sub cmd {
    local $, = ' ';
    say @_;
    system @_;
}

sub cmd_out {
    local $, = ' ';
    say @_;
    `@_`;
}
